/*
** Velo language runtime support.
** Provides OOP dot-call method binding and other Velo-specific builtins.
**
** Copyright (C) 2005-2026 Mike Pall. Velo additions by nexoniarz.
** Licensed under the Apache License, Version 2.0.
*/

#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"

/*
** Bound method closure: function(...) return m(t, ...) end
** Upvalue 1 = m (method function)
** Upvalue 2 = t (instance / self)
*/
static int velo_bound_method(lua_State *L)
{
  int nargs = lua_gettop(L);
  /* Build call: m(t, arg1, arg2, ...) */
  lua_pushvalue(L, lua_upvalueindex(1));  /* m */
  lua_insert(L, 1);                        /* m at position 1 */
  lua_pushvalue(L, lua_upvalueindex(2));  /* t */
  lua_insert(L, 2);                        /* t at position 2 */
  /* Stack: m, t, arg1, ..., argN */
  lua_call(L, nargs + 1, LUA_MULTRET);
  return lua_gettop(L);
}

/*
** Class instance __index metamethod.
** Looks up key k in the class table (cls) and, if the value is a function,
** returns a bound method closure that automatically passes the instance (t)
** as the first argument (self).
**
** Upvalue 1 = cls (the class table)
*/
static int velo_class_index(lua_State *L)
{
  /* Args: t (1), k (2) */
  lua_pushvalue(L, lua_upvalueindex(1));  /* push cls */
  lua_pushvalue(L, 2);                    /* push k */
  lua_rawget(L, -2);                      /* cls[k] -> m (rawget avoids __index recursion) */
  lua_remove(L, -2);                      /* remove cls; stack top = m */

  if (!lua_isfunction(L, -1)) {
    return 1;  /* non-function (or nil): return directly */
  }

  /* m is a function: wrap it so instance is passed as self */
  lua_pushvalue(L, 1);  /* push t (instance) */
  lua_pushcclosure(L, velo_bound_method, 2);  /* closure(m, t) */
  return 1;
}

/*
** __velo_make_index(cls) -> __index_fn
**
** Called at class definition time. Returns a closure that serves as the
** __index metamethod for instances of cls.  Each instance field access that
** resolves to a method will return a pre-bound closure: method(self, ...).
**
** Usage (generated by the parser):
**   Player.__index = __velo_make_index(Player)
*/
static int velo_make_index(lua_State *L)
{
  luaL_checktype(L, 1, LUA_TTABLE);
  lua_pushvalue(L, 1);  /* upvalue: cls */
  lua_pushcclosure(L, velo_class_index, 1);
  return 1;
}

LUALIB_API int luaopen_velo(lua_State *L)
{
  lua_pushcfunction(L, velo_make_index);
  lua_setglobal(L, "__velo_make_index");
  return 0;
}
